### ISSUE TITLE
Communication for in-class lab 2

### ISSUE THREAD

**Issue by ClarkLindsay** [ClarkLindsay/automobile#1]
@Wolfencode3000
@NickAnson

Hey, this is Clark Lindsay. If we need to communicate over this lab I would recommend we either use github issues or email. My email is clindsay6821@volmail.jalc.edu.

Just so I know you guys recieve this and it is working please respond to this issue with an "ok" or something. 

Thanks

**Comment by Wolfencode3000** [comment]
"All your base belong to us"

**Comment by NickAnson** [comment]
Sorry for late reply but present

**Comment by ClarkLindsay** [comment]
No problem. I just wanted to make sure that the issues were working (had some trouble with that) and that the tags worked
