### ISSUE TITLE
FlowChart

### ISSUE THREAD

**Issue by ClarkLindsay** [ClarkLindsay/automobile#2]
@anthonykulis
@Wolfencode3000
@NickAnson

![capture](https://cloud.githubusercontent.com/assets/25178240/25006099/35df3112-2021-11e7-8d21-511cba11d250.PNG)

Here is the flowchart for 2016 Dodge Dart SXT Sport Blacktop

**Comment by anthonykulis** [comment]
when trying to get an image of that, `download as`, then select `jpg`, then
under that `crop to content`, then select `600 dpi` for the highest res.
Also, what happened to having one path? `process -> decision -> decision ->
... -> process -> ...`

**Comment by ClarkLindsay** [comment]
Here is the improved flow chart.
![dart sxt sport blacktop - page 1](https://cloud.githubusercontent.com/assets/25178240/25089538/c0ce268c-2343-11e7-9cd7-4c7cef60e7ee.jpeg)

**Comment by NickAnson** [comment]
My UML's

Dodge dart areo:
![dodge aero - page 1](https://cloud.githubusercontent.com/assets/21188612/25090576/a23c9a22-2349-11e7-9f13-e39a73187f67.png)

Dodge Dart GT
![2016 dart gt - page 1](https://cloud.githubusercontent.com/assets/21188612/25090577/a36cb22e-2349-11e7-8a29-4c275f186215.png)

Dodge dart gt sport blacktop
![2016 dart gt sport blacktop - page 1](https://cloud.githubusercontent.com/assets/21188612/25090578/a4bb57e8-2349-11e7-9be9-077378b489be.png)

Dodge dart gt sport
![2016 dart gt sport - page 1](https://cloud.githubusercontent.com/assets/21188612/25090579/a62046d4-2349-11e7-82e6-a7ad3c181fce.png)

**Comment by Wolfencode3000** [comment]
Dart SE
![dart se - page 1](https://cloud.githubusercontent.com/assets/25177372/25090955/fdeb66a8-234b-11e7-9096-3bb147bc71c1.jpeg)

**Comment by Wolfencode3000** [comment]
Dart SXT
![dart sxt - page 1](https://cloud.githubusercontent.com/assets/25177372/25090975/0fa52e6a-234c-11e7-8eb5-d9967c72e9f5.jpeg)

**Comment by Wolfencode3000** [comment]
Dart SXT Sport
![dart sxt sport - page 1](https://cloud.githubusercontent.com/assets/25177372/25090983/1eefee78-234c-11e7-8ae3-e10f34bc3f10.jpeg)

**Comment by Wolfencode3000** [comment]
Dart SXT Sport
![dart sxt sport - page 1](https://cloud.githubusercontent.com/assets/25177372/25091010/4644a20c-234c-11e7-9ee3-c3c57e8c91b3.jpeg)

**Comment by anthonykulis** [comment]
why dont you all have an issue per flowchart like i asked? so what, am I
misreading this or are you going to have 1 issue for 7 things to do?

**Comment by NickAnson** [comment]
Hey guys I'm not going to be there tomorrow as I have a school event that I
have to go to but I can do whatever you guys post/ask here
