### ISSUE TITLE
Meeting

### ISSUE THREAD

**Issue by ClarkLindsay** [ClarkLindsay/automobile#4]
@NickAnson
@Wolfencode3000

Hey, guys, I am thinking that it would be a good idea for us all to set a time to meet and discuss this project. I am available tomorrow after 2:00 and before 7:00. I am also available Thursday after 2:00. If neither of these times work for either one of you, please respond with a time that will. I will try to work it out where all three of us can meet. Thanks.

-Clark

**Comment by NickAnson** [comment]
I won't be able to meet tomorrow at all due to being 3 hours away taking a
test but Thursday after 5 would be good if you guys are wanting to wait
that late if not it's all good

**Comment by Wolfencode3000** [comment]
i dont have any time in the afternoon, i have work the rest of the week right after class. Only time im available is right after class to 1pm

**Comment by Wolfencode3000** [comment]
Sorry i missed this morning, totally overslept the alarm clock
