### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by ClarkLindsay** [ClarkLindsay/automobile#5]
@NickAnson
@Wolfencode3000

Hey, guys, Mr. Kulis wants us to post our flowcharts/UMLs in separate issues. Also, he wants you guys to make pull requests even if you aren't done yet. Just make one for what you have and I will comment as needed. Thanks!

-Clark

**Comment by NickAnson** [comment]
Sure ill post mine later tonight prob and ill have wheels and tires done later tonight

**Comment by ClarkLindsay** [comment]
Thanks Nick.

**Comment by NickAnson** [comment]
Quick question how do you suggest I name tire names?

**Comment by ClarkLindsay** [comment]
I would recommend naming them by width (the first three numbers). So the 225/45R17 would be Width225. That is just a suggestion. If it does not work I would ask Mr. Kulis.

**Comment by NickAnson** [comment]
I just gonna start on my builders for the night just finished wheels and
tires now in case you want to use em. I just made one tire class since they
are all all season tires, which I just made a set details method to change
what you want about the tire due to it being a better solution and has
better scalability in my opinion

**Comment by ClarkLindsay** [comment]
Awesome!

**Comment by ClarkLindsay** [comment]
Hey, Nick, I was looking at your code and have a coupe of suggestions for your builder. First, Mr. Kulis showed us how to avoid using long switch statements with an Arraylist (check out my code to see it). Second he suggested that we use addOption(new x()) to avoid DRy code. Third, I think that your Automobile builder is passing the wrong parameters. The syntax is (String, String, String, body, driveline, engine assembly, suspension). This is not what you pass and your code threw an error when I tried it that way. Thanks.

-Clark
